version: 0.0
os: linux
files:
  - source: /project1.war
    destination: /usr/local/apache-tomcat-8.5.8/webapps/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

